apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: app
spec:
  replicas: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      app: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: server
          imagePullPolicy: Never
      restartPolicy: Always