apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      containers:
        - name: server
          image: k8s-metadata-example-test2:latest
          ports:
            - containerPort: 8080
      initContainers:
        - name: wait
          image: busybox:1.34
          command: ['sh', '-c', 'sleep 5']
