apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/deployment-with-svc
patchesStrategicMerge:
  - deployment.yaml
  - svc.yaml
namePrefix: test2-
commonLabels:
  app: test2